runtime: python310 

env_variables:
  FIREBASE_TYPE: "service_account"
  FIREBASE_PROJECT_ID: "test-bone-b6e69"
  FIREBASE_PRIVATE_KEY_ID: "4d8f5c2db2f7470a410c97bc36a391cf2e38c758"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoGRxooCnKzYzSx16foxdycGJIoMvPGFeSHw73DitzyAzuq4Ei1LI1unczkrZYw0YCfXjaeR/wg0d8jObFLe+HCe4s9HWO4il3ePcseW19jKJbDrxQuKbdXFop+4CA+AsZMUt73N7n2dtt... (rest of private key here)"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fdfda@test-bone-b6e69.iam.gserviceaccount.com"
  FIREBASE_CLIENT_ID: "113273384621342302025"
  FIREBASE_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  FIREBASE_TOKEN_URI: "https://oauth2.googleapis.com/token"
  FIREBASE_AUTH_PROVIDER_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  FIREBASE_CLIENT_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fdfda%40test-bone-b6e69.iam.gserviceaccount.com"
r